ALTER TABLE cpu
ALTER
COLUMN architecture TYPE VARCHAR(255) USING (architecture::VARCHAR(255));

ALTER TABLE gpu
ALTER
COLUMN architecture TYPE VARCHAR(255) USING (architecture::VARCHAR(255));

ALTER TABLE cpu
ALTER
COLUMN manufacturer TYPE VARCHAR(255) USING (manufacturer::VARCHAR(255));

ALTER TABLE generic_component
ALTER
COLUMN manufacturer TYPE VARCHAR(255) USING (manufacturer::VARCHAR(255));

ALTER TABLE gpu
ALTER
COLUMN manufacturer TYPE VARCHAR(255) USING (manufacturer::VARCHAR(255));

ALTER TABLE memory_module
ALTER
COLUMN manufacturer TYPE VARCHAR(255) USING (manufacturer::VARCHAR(255));

ALTER TABLE network_device
ALTER
COLUMN manufacturer TYPE VARCHAR(255) USING (manufacturer::VARCHAR(255));

ALTER TABLE storage
ALTER
COLUMN manufacturer TYPE VARCHAR(255) USING (manufacturer::VARCHAR(255));

ALTER TABLE cpu
ALTER
COLUMN model TYPE VARCHAR(255) USING (model::VARCHAR(255));

ALTER TABLE generic_component
ALTER
COLUMN model TYPE VARCHAR(255) USING (model::VARCHAR(255));

ALTER TABLE gpu
ALTER
COLUMN model TYPE VARCHAR(255) USING (model::VARCHAR(255));

ALTER TABLE memory_module
ALTER
COLUMN model TYPE VARCHAR(255) USING (model::VARCHAR(255));

ALTER TABLE network_device
ALTER
COLUMN model TYPE VARCHAR(255) USING (model::VARCHAR(255));

ALTER TABLE storage
ALTER
COLUMN model TYPE VARCHAR(255) USING (model::VARCHAR(255));

ALTER TABLE computer
ALTER
COLUMN name TYPE VARCHAR(255) USING (name::VARCHAR(255));

ALTER TABLE consumer
ALTER
COLUMN name TYPE VARCHAR(255) USING (name::VARCHAR(255));

ALTER TABLE cpu
ALTER
COLUMN name TYPE VARCHAR(255) USING (name::VARCHAR(255));

ALTER TABLE generic_component
ALTER
COLUMN name TYPE VARCHAR(255) USING (name::VARCHAR(255));

ALTER TABLE gpu
ALTER
COLUMN name TYPE VARCHAR(255) USING (name::VARCHAR(255));

ALTER TABLE memory_module
ALTER
COLUMN name TYPE VARCHAR(255) USING (name::VARCHAR(255));

ALTER TABLE network_device
ALTER
COLUMN name TYPE VARCHAR(255) USING (name::VARCHAR(255));

ALTER TABLE nonce
ALTER
COLUMN name TYPE VARCHAR(255) USING (name::VARCHAR(255));

ALTER TABLE provider
ALTER
COLUMN name TYPE VARCHAR(255) USING (name::VARCHAR(255));

ALTER TABLE staff
ALTER
COLUMN name TYPE VARCHAR(255) USING (name::VARCHAR(255));

ALTER TABLE storage
ALTER
COLUMN name TYPE VARCHAR(255) USING (name::VARCHAR(255));