ALTER TABLE cpu
ALTER
COLUMN architecture SET DATA TYPE VARCHAR(255);

ALTER TABLE gpu
ALTER
COLUMN architecture SET DATA TYPE VARCHAR(255);

ALTER TABLE cpu
ALTER
COLUMN manufacturer SET DATA TYPE VARCHAR(255);

ALTER TABLE generic_component
ALTER
COLUMN manufacturer SET DATA TYPE VARCHAR(255);

ALTER TABLE gpu
ALTER
COLUMN manufacturer SET DATA TYPE VARCHAR(255);

ALTER TABLE memory_module
ALTER
COLUMN manufacturer SET DATA TYPE VARCHAR(255);

ALTER TABLE network_device
ALTER
COLUMN manufacturer SET DATA TYPE VARCHAR(255);

ALTER TABLE storage
ALTER
COLUMN manufacturer SET DATA TYPE VARCHAR(255);

ALTER TABLE cpu
ALTER
COLUMN model SET DATA TYPE VARCHAR(255);

ALTER TABLE generic_component
ALTER
COLUMN model SET DATA TYPE VARCHAR(255);

ALTER TABLE gpu
ALTER
COLUMN model SET DATA TYPE VARCHAR(255);

ALTER TABLE memory_module
ALTER
COLUMN model SET DATA TYPE VARCHAR(255);

ALTER TABLE network_device
ALTER
COLUMN model SET DATA TYPE VARCHAR(255);

ALTER TABLE storage
ALTER
COLUMN model SET DATA TYPE VARCHAR(255);

ALTER TABLE computer
ALTER
COLUMN name SET DATA TYPE VARCHAR(255);

ALTER TABLE consumer
ALTER
COLUMN name SET DATA TYPE VARCHAR(255);

ALTER TABLE cpu
ALTER
COLUMN name SET DATA TYPE VARCHAR(255);

ALTER TABLE generic_component
ALTER
COLUMN name SET DATA TYPE VARCHAR(255);

ALTER TABLE gpu
ALTER
COLUMN name SET DATA TYPE VARCHAR(255);

ALTER TABLE memory_module
ALTER
COLUMN name SET DATA TYPE VARCHAR(255);

ALTER TABLE network_device
ALTER
COLUMN name SET DATA TYPE VARCHAR(255);

ALTER TABLE nonce
ALTER
COLUMN name SET DATA TYPE VARCHAR(255);

ALTER TABLE provider
ALTER
COLUMN name SET DATA TYPE VARCHAR(255);

ALTER TABLE staff
ALTER
COLUMN name SET DATA TYPE VARCHAR(255);

ALTER TABLE storage
ALTER
COLUMN name SET DATA TYPE VARCHAR(255);
